#!/usr/bin/bash

wall="$HOME/.config/wall.png"

if [ $# -eq 0 ]
then
  cp -f `find $HOME/pictures/wallpapers -type f |shuf -n 1` $wall
else
  cp $1 $wall
fi
echo "$wall"
xwallpaper --zoom $wall&&wal -c&&wal -i $wall >/dev/null&&sed -i '/SchemeUrg/d' $HOME/.cache/wal/colors-wal-dwm.h&&cd $HOME/mydwm && sudo make clean install >/dev/null


